increase step output from tests and yaml lint

diff --git a/.github/workflows/dart-unit-tests-on-pr.yml b/.github/workflows/dart-unit-tests-on-pr.yml
--- a/.github/workflows/dart-unit-tests-on-pr.yml
+++ b/.github/workflows/dart-unit-tests-on-pr.yml
@@ -1,6 +1,6 @@
 name: Dart Unit Tests for PRs
 
-on:
+"on":
   workflow_dispatch:
   pull_request:
     branches: ["**"]
@@ -22,8 +22,30 @@ jobs:
         if: always()
 
       - name: Run tests with coverage enabled
-        run: dart test --coverage=.artefacts/coverage
-        if: always()
+        shell: bash
+        run: | # Create test logs and output if failed to step summary
+          set -o pipefail
+          mkdir -p .artefacts/test-logs
+          dart test --coverage=.artefacts/coverage 2>&1 \
+            | tee .artefacts/test-logs/dart-test.log
+          TEST_EXIT_CODE=${PIPESTATUS[0]}
+          {
+            echo "## Unit test results"
+            if [ "$TEST_EXIT_CODE" -eq 0 ]; then
+              echo ""
+              echo "Tests passed."
+            else
+              echo ""
+              echo "Tests failed."
+            fi
+            echo ""
+            echo "### Last 50 lines of output"
+            echo '```text'
+            tail -n 50 .artefacts/test-logs/dart-test.log
+            echo '```'
+          } >> "$GITHUB_STEP_SUMMARY"
+          exit "$TEST_EXIT_CODE"
+       if: always()
 
       - name: Archive raw coverage artifacts
         if: always()
@@ -34,7 +56,7 @@ jobs:
 
   code-coverage:
     needs: unit-tests
-    if: ${{ needs.unit-tests.result == 'success' }} 
+    if: ${{ needs.unit-tests.result == 'success' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
@@ -55,14 +77,15 @@ jobs:
           name: raw-coverage
           path: .artefacts/coverage
 
-      - name: test coverage availability
-        run: |
-          ls -la .artefacts/coverage
-
       - name: Convert to LCOV report
         run: |
           dart pub global activate coverage
-          dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o .artefacts/coverage/lcov.info -i .artefacts/coverage
+          dart pub global run coverage:format_coverage \
+            --packages=.dart_tool/package_config.json \
+            --report-on=lib \
+            --lcov \
+            -o .artefacts/coverage/lcov.info \
+            -i .artefacts/coverage
 
       - name: Generate HTML coverage report
         run: |
